version: "3"
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.2
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs/:/logs/
    # command:
    #   - "/bin/sh"
    #   - "-c"
    #   - |
    #     filebeat -e -strict.perms=false
