version: '3'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.9.1
    volumes:
      - ./logstash/config/logstash.yml/:/usr/share/logstash/config/logstash.yml:ro
      # - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044"
      - "5011:5011"
      - "5012:5012"
      - "5013:5013"
